# Generated by Django 5.0.6 on 2024-07-10 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Columna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo_haz', models.CharField(blank=True, max_length=45, null=True)),
                ('frecuencia', models.CharField(blank=True, max_length=45, null=True)),
                ('ancho_banda', models.CharField(blank=True, max_length=45, null=True)),
                ('amortiguamiento', models.CharField(blank=True, max_length=45, null=True)),
                ('modelo', models.CharField(blank=True, max_length=45, null=True)),
                ('ganancia', models.CharField(blank=True, max_length=45, null=True)),
                ('velocidad', models.CharField(blank=True, max_length=45, null=True)),
                ('retardo', models.CharField(blank=True, max_length=45, null=True)),
                ('diametro', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcesoInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimiento', models.CharField(blank=True, max_length=45, null=True)),
                ('material', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ubicacion', models.CharField(blank=True, max_length=45, null=True)),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.analista')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.procesoinspeccion')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.area')),
            ],
        ),
        migrations.CreateModel(
            name='Faja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
                ('nPoleas', models.CharField(blank=True, max_length=45, null=True)),
                ('codigo', models.CharField(blank=True, max_length=45, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('columna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.columna')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inspector')),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.fila')),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(blank=True, max_length=45, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.documentos')),
            ],
        ),
        migrations.CreateModel(
            name='Mediciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.parametros')),
            ],
        ),
        migrations.CreateModel(
            name='Poleas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
                ('faja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.faja')),
            ],
        ),
        migrations.CreateModel(
            name='PoleasProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.poleas')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.procesoinspeccion')),
            ],
        ),
        migrations.AddField(
            model_name='parametros',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.procesoinspeccion'),
        ),
        migrations.CreateModel(
            name='FajasProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.faja')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.procesoinspeccion')),
            ],
        ),
        migrations.CreateModel(
            name='Tabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfilas', models.IntegerField(blank=True, null=True)),
                ('ncol', models.IntegerField(blank=True, null=True)),
                ('medicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.mediciones')),
            ],
        ),
        migrations.AddField(
            model_name='fila',
            name='tabla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.tabla'),
        ),
        migrations.AddField(
            model_name='columna',
            name='tabla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.tabla'),
        ),
    ]
